### PR TITLE
Constraints

### PR DESCRIPTION
**Pull request by wimspaargaren**
Pls check this branch out.

### CODE REVIEW

**Comment by rpjproost** [comment]
Checked maven site. 
- No checkstyle
- No PMD/CPD
- No Findbugs (except for database, but that's on sprintplan)
- Everything working for this week.

**Comment by pascalremeijsen** [comment]
After maven site, no PMD, findbugs or checkstyle errors found.
Good to go !

**Comment by jelmerdeboer** [comment]
Everything is fine, expect on the FindBugs we already knew. No PMD and Checkstyle is ok! Cobertura is ok

**Comment by ArnoutvdKnaap** [comment]
wait for travis

**Comment by jelmerdeboer** [comment]
Hooray for travis

**Pull request merged**
