### PR TITLE
Chunk on period

### PR DESCRIPTION
**Pull request by ArnoutvdKnaap**
added chunking on period functionality. following grammer:
chunk date <nr of days>

### CODE REVIEW

**Comment by pascalremeijsen** [comment]
no errors introduced.
This can be merged.

**Comment by pascalremeijsen** [comment]
no errors introduced.
this can be merged.

**Comment by pascalremeijsen** [comment]
no errors introduced.
this can be merged.

**Comment by wimspaargaren** [comment]
No PMD, Checkstyle or findbugs. I'll merge.

**Pull request merged**
