### PR TITLE
Codepageimplementation

### PR DESCRIPTION
**Pull request by jelmerdeboer**

### CODE REVIEW

**Comment by ArnoutvdKnaap** [comment]
Has checkstyle but wil be fixed today. If travis is ok, can be merged.

**Comment by wimspaargaren** [comment]
Contains some checkstyle, but this is because we going to implement extra functionallity for the codepage. I think it can be merged!

**Comment by rpjproost** [comment]
Worked closely with wim, so I know the code is ok. 
And what arnout says is correct.

**Comment by pascalremeijsen** [comment]
no serious problems.
this can be merged.

**Pull request merged**
