### PR TITLE
Xml test update

### PR DESCRIPTION
**Pull request by ArnoutvdKnaap**
updates the xml tests to cover more of the xml parser and clean up db tables.

### CODE REVIEW

**Comment by rpjproost** [comment]
Looks good, what is the xmltestparser exactly?

**Comment by rpjproost** [comment]
Pulled this, and saw this error printed in console:
[Fatal Error] noEnd.xml:20:13: XML document structures must start and end within the same entity.

**Comment by ArnoutvdKnaap** [comment]
The xmltestParser is a parser that extends xmlParser, so has al the same functionality, but replaces the standard parser with a parser that doesn't do anyting. This way only xmlParser is tested.

The fatal error is printed by the libary that processes the xml file.  It is part of 1 of the tests and put there on purpose. The error is not closing the last node with: </xml> in the noEnd.xml file.

**Comment by wimspaargaren** [comment]
Looks good. Still 1 chekstyle error on the stackoverflow link though. You could fix it by splitting the link in half.

**Comment by rpjproost** [comment]
The checkstyle error isn't that bad, probably removed later on in the project so I guess this can be merged :+1:

**Pull request merged**
