### PR TITLE
Database clean up

### PR DESCRIPTION
**Pull request by rpjproost**
Edited a lot of files in the process of cleaning up database, because of
deletion of unused method, or extending them with more variables.

-Created new class SQLBuilder
This creates every query we use, database has no more string
concatenation.
Every method is as small as possible, and long method names.

-DB class
Removed a lot of methods, switched them over to SQLBuilder and adjusted
them accordingly.
Also renamed an method and added more variables to a method.
We had 3 different select methods?....
Removed one entirely, adjusted the other two to be different kind of
selects.

-Tests
Mostly changed tests that were running that one select I entirely
removed. Also adjusted some lines so they would work with the two
different select methods.

-All
- no checkstyle warnings
- no PMD/CPD
- Cobertura test coverage did not really change
- Every test still working
- FINDBUGS HAS ONE BUG

-FINDBUGS
may fail to clean up java.sql.Statement on checked exception
However I clean it up everywhere, but in different methods, should this
be changed? If yes, how???

### CODE REVIEW

**Comment by pascalremeijsen** [comment]
After maven site only the one findbugs error found.
I don't know how to fix this, but because of the nature of the error, I think we can still merge it.
No serious problems found.

**Comment by jelmerdeboer** [comment]
The findbugs means that the connect you make, must have be nicely try/catch/finally thingies. Where you in the finally the connection close, but that must be in a try/finally block also etc...
For me it is crazy to do this. So PMD, FindBugs and Cobertura is ok for me.

Checkstyle thingies: 
 - The SQLBuilder createTableColumns method contains a out-commented line of code
 - MergeTable has no useful JavaDoc for the class itself and constructor
 - Database class has no JavaDoc for the class itself and please remove the @author

**Comment by wimspaargaren** [comment]
I adjusted some last things, but all looks fine. If travis passes this can be merged.

**Comment by ArnoutvdKnaap** [comment]
travis succeeds so ill merge

**Pull request merged**
