### PR TITLE
CleanedUp the ExcelParser and TXTParser Class.

### PR DESCRIPTION
**Pull request by wimspaargaren**
Made methods which should be private, private and split some long methods into smaller ones.

### CODE REVIEW

**Comment by pascalremeijsen** [comment]
looks good to me! This can be merged.

**Comment by rpjproost** [comment]
Looks better indeeed :+1:

**Comment by jelmerdeboer** [comment]
Everything is good!
Only missing a JavaDoc at the parse method in excelparser

**Comment by ArnoutvdKnaap** [comment]
just add javaDoc and then merge it

**Pull request merged**
