### PR TITLE
Excel to db

### PR DESCRIPTION
**Pull request by wimspaargaren**
Hi Guys,

Here is a short summary of the new features in this branch:
* Connected the Excel Parser with the database.
* Added tests for all different files to see if they actually store the values into the database.
* Added functionallity for all dates to be formatted right into sql
* Added a filewriter which output for spss. Above the class you'll find a link of how the txt file for spss should be formatted, but since I don't have any experience with it you could check if this is correct.
* Added a simple test for the filewriter.
* Rick cleaned up the database code.
* Added hashcode to Column class.

### CODE REVIEW

**Comment by pascalremeijsen** [comment]
Didn't find any problem. Looks good.
For next time: maybe, more pull requests instead of 1 big request.
This was a LOT of code to go through.

**Comment by jelmerdeboer** [comment]
I found 5 FindBugs problems:
 -> 3 in the Db class
 -> 1 in the TXTParser
 -> 1 in the WriteToTXT
Also 2 new CheckStyle fault, but those are referending to TODO methods so that's fine.
You guys missing test for the SingletonDb, don't know if you need them now.

Check the mavensite for all details ;)

**Comment by wimspaargaren** [comment]
Ok. We'll check FindBugs and checkstyle tomorrow. And yes Pascal we'll try to do that next time ;)

**Comment by ArnoutvdKnaap** [comment]
last findbugs problems are for a depricated method, which will be removed in a future update.

**Pull request merged**
